# Generated by Django 4.1.4 on 2023-06-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'verbose_name_plural': 'Courses'},
        ),
    ]
