# Generated by Django 4.1.4 on 2023-06-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'verbose_name_plural': 'StudentsModel'},
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='current_degree',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
